name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install aliyun cli
        run: |
          curl -o aliyun-cli-linux-latest-amd64.tgz https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
          tar -xvzf aliyun-cli-linux-latest-amd64.tgz
          sudo mv aliyun /usr/local/bin/
      
      - name: Configure aliyun cli
        run: |
          aliyun configure set \
            --profile default \
            --mode AK \
            --region cn-hangzhou \
            --access-key-id ${{ secrets.ALICLOUD_ACCESS_KEY }} \
            --access-key-secret ${{ secrets.ALICLOUD_SECRET_KEY }}
      
      - name: Login to ACR
        run: |
          aliyun cr GET-LOGIN-PASSWORD | docker login \
            --username ${{ secrets.ALICLOUD_ACCESS_KEY }} \
            --password-stdin \
            crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com
      
      - name: Build and push
        run: |
          docker build -t crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com/comfyui111/comfyui31011:latest .
          docker push crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com/comfyui111/comfyui31011:latest