name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com
          username: anjsy  # 使用阿里云账号全名
          password: ${{ secrets.ACR_PASSWORD }}  # 使用容器镜像服务的登录密码
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com/comfyui111/comfyui31011:latest
            crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com/comfyui111/comfyui31011:${{ github.sha }}