name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to ACR
        run: |
          echo "${{ secrets.ALICLOUD_SECRET_KEY }}" | docker login --username "${{ secrets.ALICLOUD_ACCESS_KEY }}" --password-stdin crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com
      
      - name: Build and push
        run: |
          docker build -t crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com/comfyui111/comfyui31011:latest .
          docker push crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com/comfyui111/comfyui31011:latest