name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_REGISTRY: crpi-0ph7u9lth4oj58qr.cn-hangzhou.personal.cr.aliyuncs.com
  ACR_NAMESPACE: comfyui111
  IMAGE_NAME: comfyui31011

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to ACR
        env:
          ACR_USERNAME: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          ACR_PASSWORD: ${{ secrets.ALICLOUD_SECRET_KEY }}
        run: |
          echo "$ACR_PASSWORD" | docker login $ACR_REGISTRY -u $ACR_USERNAME --password-stdin
      
      - name: Build and push image
        run: |
          docker build -t $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:latest .
          docker push $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:latest